from transformers import AutoImageProcessor

from custom_models.qwen2_5_vl_3b_mspe.A_image_processor import Qwen2VLImageProcessor
from custom_models.qwen2_5_vl_3b_mspe.configuration_qwen2_5_vl import Qwen2_5_VLVisionConfig
AutoImageProcessor.register(config_class=Qwen2_5_VLVisionConfig, image_processor_class=Qwen2VLImageProcessor)


processor = AutoImageProcessor.from_pretrained("custom_models/qwen2_5_vl_3b_mspe")
