### model
#model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
model_name_or_path: /home/tiger/LLaMA-Factory/custom_models/qwen2_5_vl_3b_mspe/
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false
freeze_multi_modal_projector: false
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
#dataset: mllm_demo,identity,alpaca_en_demo
dataset: llava_779k
#llava_779k, llava_150k_en
template: qwen2_vl
cutoff_len: 8192
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 256
dataloader_num_workers: 16
#streaming: true
## 779289/128
#max_steps: 6088

### output
output_dir: saves/qwen2_5vl-3b/full/sft
logging_steps: 10
save_steps: 2500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
#report_to: none
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: qwen2.5-vl-3b

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8 # 128/8/2
learning_rate: 2e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
